version: "3.5"
services:

  keycloak_db:
    image: postgres
    container_name: node_sand-box_keycloak_db
    ports:
      - 5432:5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  keycloak:
    image: ghcr.io/m0rgan01/keycloak-sand-box:main
    container_name: node_sand-box_keycloak
    ports:
      - 8443:8443
      - 8080:8080
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: node_sand-box_keycloak_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HOSTNAME: localhost
    depends_on:
      - keycloak_db

  mailhog:
    image: mailhog/mailhog
    container_name: node_sand-box_mailer
    ports:
      - 8025:8025
      - 1025:1025
    restart: always

  app_db:
    image: postgres
    container_name: node_sand-box_db
    ports:
      - 5433:5433
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    environment:
      PGPORT: 5433
      POSTGRES_DB: app_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    restart: always

volumes:
  keycloak_postgres_data:
  app_postgres_data: