version: "3.5"
services:

  keycloak_db:
    image: postgres
    container_name: node_sand-box_keycloak_db
    ports:
      - 5432:5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  keycloak:
    image: ghcr.io/m0rgan01/keycloak-sand-box:main
    container_name: node_sand-box_keycloak
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: node_sand-box_keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KEYCLOAK_IMPORT: opt/jboss/keycloak/imports/realm-export.json
    depends_on:
      - keycloak_db

  mailhog:
    image: mailhog/mailhog
    container_name: node_sand-box_mailer
    ports:
      - 8025:8025
      - 1025:1025
    restart: always

  app_db:
    image: postgres
    container_name: node_sand-box_db
    ports:
      - 5433:5433
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    environment:
      PGPORT: 5433
      POSTGRES_DB: app_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    restart: always

volumes:
  keycloak_postgres_data:
  app_postgres_data: