version: "3.5"
services:

  keycloak_db:
    image: postgres
    container_name: node_sand-box_keycloak_db
    ports:
      - 5432:5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always

  keycloak:
    image: jboss/keycloak:12.0.1
    container_name: node_sand-box_keycloak
    volumes:
      - ./keycloak/imports/:/opt/jboss/keycloak/imports
    expose:
      - 8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: node_sand-box_keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KEYCLOAK_IMPORT: opt/jboss/keycloak/imports/realm-export.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host(`localhost`)
    depends_on:
      - keycloak_db

  traefik:
    image: traefik:v2.3
    container_name: node_sand-box_treafik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mailhog:
    image: mailhog/mailhog
    container_name: node_sand-box_mailer
    ports:
      - 8025:8025
      - 1025:1025
    labels:
      - traefik.enable=true
      - traefik.http.services.mailhog.loadbalancer.server.port=8025
      - traefik.http.routers.mailhog.rule=Host(`mailhog.localhost`)
    restart: always

volumes:
  keycloak_postgres_data: