name: Heroku deploiement

on:
  push:
    branches:
      - master

jobs:

  build-and-publish-api:
    name: Build API image for production and push to Heroku registry
    runs-on: ubuntu-latest
    env:
      APP_NAME: node-sand-box
      IID_FILE: imageid.txt
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Docker Buil
        run: docker build --iidfile ${{ env.IID_FILE  }} -t registry.heroku.com/${{ env.APP_NAME  }}/app .

      - name: Login to Heroku registry
        run: docker login -u _ -p ${{ secrets.HEROKU_TOKEN  }} registry.heroku.com

      - name: Push image to Heroku registry
        run: docker push registry.heroku.com/${{ env.APP_NAME  }}/app

      - name: Show image ID
        run: echo "Docker Image ID is $(cat ${{ env.IID_FILE  }})"

      - name: Release in Heroku
        run: >-
          curl -X PATCH https://api.heroku.com/apps/${{ env.APP_NAME  }}/formation 
          --header "Content-Type: application/json" 
          --header "Accept: application/vnd.heroku+json; version=3.docker-releases" 
          --header "Authorization: Bearer ${{ secrets.HEROKU_TOKEN  }}" 
          --data '
            { 
              "updates": [ 
                { 
                  "type": "web", 
                  "docker_image": "'$(cat ${{ env.IID_FILE  }})'" 
                } 
              ]
            }'